packages:
  - packages/*
  - apps/*

allowBuilds:
  '@mongodb-js/zstd': false
  node-liblzma: false
  esbuild: true
  simple-git-hooks: true

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@fisch0920/config'
